
package View.pages;

import Modelo.interfaz.StatusType;
import View.Swing.Tabla;
import java.awt.Color;

/**
 *
 * @author david
 */
public class Page_Pedidos extends javax.swing.JPanel {

    /**
     * Creates new form Page_Pedidos
     */
    public Page_Pedidos() {
        initComponents();
        
        sptabla.getViewport().setBackground(Color.WHITE);
        
        init();
    }
    
    final public void init(){
        lbtabla.addRow(new Object[]{"1","Juan","2","Productos...",StatusType.COMPLETADO});
        lbtabla.addRow(new Object[]{"2","Mesa2","1","Productos...",StatusType.ENPROCESO});
        lbtabla.addRow(new Object[]{"3","Jose","2","Productos...",StatusType.COMPLETADO});
        lbtabla.addRow(new Object[]{"4","Mesa10","1","Productos...",StatusType.PENDIENTE});
        lbtabla.addRow(new Object[]{"5","Maria","2","Productos...",StatusType.ENPROCESO});
        lbtabla.addRow(new Object[]{"6","Mesa1","1","Productos...",StatusType.ENPROCESO});
        lbtabla.addRow(new Object[]{"7","Mesa17","1","Productos...",StatusType.PENDIENTE});
        lbtabla.addRow(new Object[]{"8","Daniela","2","Productos...",StatusType.COMPLETADO});
        lbtabla.addRow(new Object[]{"9","Santiago","2","Productos...",StatusType.COMPLETADO});
        lbtabla.addRow(new Object[]{"10","David","2","Productos...",StatusType.COMPLETADO});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new View.Swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        sptabla = new javax.swing.JScrollPane();
        lbtabla = new View.Swing.Tabla();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(130, 130, 130));
        jLabel1.setText("Pedidos Domicilios");

        sptabla.setBorder(null);

        lbtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CLIENTE", "TIPO", "DESCRIPCION", "ESTADO"
            }
        ));
        sptabla.setViewportView(lbtabla);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sptabla, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sptabla, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private View.Swing.Tabla lbtabla;
    private View.Swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane sptabla;
    // End of variables declaration//GEN-END:variables
}
